server:
  port: 6060

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

security:
  private-key-file: docflow-authorization.jks
  key-pass: 123456
  key-alias: docflow-authorization

spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.username: sa
spring.datasource.password:
spring.datasource.initialization-mode: always

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate